name: 1vs1
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: 1.0.1 [Rewriten]
description: 1vs1 minigame plugin
author: CzechPMDevs
authors: [VixikCZ]
main: onevsone\OneVsOne

commands:
  1vs1:
    description: 1vs1 commands

permissions:
  1vs1.cmd:
    description: Permission for all 1vs1 commands
    default: op
